# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        autowire: true
        autoconfigure: true
        public: false
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\:
        autowire: true
        autoconfigure: true
        public: false
        resource: '../src/Service/*'
        bind:
            string $wsApiUrl: "%env(API_URL)%"
            string $wsApiUseName: "%env(API_USERNAME)%"
            string $WsApiPass: "%env(API_PASSWORD)%"

#    api.order_manager:
#        class: App\src\Service\WsClient
#        arguments:
#            - "%env(API_URL)%"
#            - "%env(API_USERNAME)%"
#            - "%env(API_PASSWORD)%"
#            - "@http_client"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
